[package]
name = "rnalib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
concat-idents = "1.1.4"
const-str = "0.5.3"

[profile.release]
lto = true